#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-3 -d 6 7 8 9 10

bspc config active_border_color \#9A7ECC
bspc config normal_border_color \#4E5173
bspc config focused_border_color \#C678DD
bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# polybar
sh /home/jack/.config/polybar/launch.sh
nitrogen --restore
